Update vqa_model.py
TypeError: ModuleUtilsMixin.get_extended_attention_mask() got an unexpected keyword argument 'device'
new data type attribute is added.